### ISSUE TITLE
Error cloning lesson

### ISSUE THREAD

**Issue by yoyothesheep** [learn-co-students/python-dictionaries-readme-data-science-pilot#2]
https://cl.ly/1i0o1P383C0K
<img width="1202" alt="screen shot 2018-03-15 at 10 27 35 pm" src="https://user-images.githubusercontent.com/33908481/37500511-49f7c3fc-28a0-11e8-8132-4e9f52c2f8dc.png">

**Comment by yoyothesheep** [comment]
Once this happens on 1 lesson, it happens for other lessons too.

**Comment by talum** [comment]
@yoyothesheep Closing this. Believe this happened b/c you changed your GitHub username.

**Comment by yoyothesheep** [comment]
OK. Re-oauthed Github this morning and this lesson loads again.
